### ISSUE TITLE
Why i not see arrows?

### ISSUE THREAD

**Issue by dobcrypto** [BeerK0in/gunbot-monitor#3]
Why i see it?
https://image.prntscr.com/image/e76282f50420447aa94e8197f134ff49.png

**Comment by toSvenson** [comment]
Pull request with fix #5

**Comment by dobcrypto** [comment]
@toSvenson what i need to do?
npm install -g gunbot-monitor
again or nothing to do?

**Comment by BeerK0in** [comment]
Sorry, I disabled email notifications so I was unaware of all the issues and the PRs here. Will look at it in a few hours.

**Comment by BeerK0in** [comment]
Updated. 

@dobcrypto Yes, just run `npm install -g gunbot-monitor`

@toSvenson Thanks a lot for your PR!
