### ISSUE TITLE
Support for the new GB 3.3.3 and greater

### ISSUE THREAD

**Issue by vbootstrap** [BeerK0in/gunbot-monitor#36]
Please!!!!!!  GB is not as easy to monitor with you.

**Comment by devboxr** [comment]
Any update? Since it completely changed it probably requires some major rework.

Would be great though!

**Comment by BeerK0in** [comment]
Non of the existing (monitoring) tools will work with Gunbot v3.3.3+ right now. The Gunbot has evolved a lot and the 3rd party devs need to adapt. This will take a while.

**Comment by arnthorsnaer** [comment]
@BeerK0in can we help somehow? can hold my own in javascript.

**Comment by BeerK0in** [comment]
@arnthorsnaer We need to wait for Gunthar to release the Gunbot API. As long as Gunbot 3.3+ does not write any logs, there is very little we can do.

**Comment by arnthorsnaer** [comment]
Gotcha!

**Comment by tandyuk** [comment]
https://gist.github.com/tandyuk/162a7e448ab8a9220ed5ee9141d0fe5a

This is my script to launch each GB5 pair as its own instance, with standard pm2 logging.
I dont know if this helps you update gmon for it, but feel free to use/rewrite that!

**Comment by BeerK0in** [comment]
Updated version supports Gunbot v9 now.
