### ISSUE TITLE
Parsing one log-file instead of multiple trade-pairs

### ISSUE THREAD

**Issue by magicdude4eva** [BeerK0in/gunbot-monitor#37]
Hi there,

I am running GB via supervisord and for each exchange (i.e. instances for Binance, Bitfinex etc).

In your code I noticed that you rely on log-files for markets with trade-pairs - i.e. `filePath = ${pathToGunbot}${market}-${tradePair}-log.txt;`.

Is there any way to make this work for `filePath = ${pathToGunbot}${market}-log.txt;`?

**Comment by BeerK0in** [comment]
Hi, this project is not maintained anymore, since the layout of the log output has changed in gunbot v3.3.3
Feel free to fork this project and change the code to your liking.

**Comment by BeerK0in** [comment]
Updated version supports Gunbot v9 now.
