### ISSUE TITLE
downgrade possible?

### ISSUE THREAD

**Issue by vaudois** [BeerK0in/gunbot-monitor#4]
hi!
is possible to downgrade to version 0.0.1 ?

im not view correct the new monitor 
![monitor](https://cloud.githubusercontent.com/assets/28846568/26416961/f97d5c46-40b7-11e7-979e-754fa7cc3ad0.jpg)

**Comment by BeerK0in** [comment]
You could run `npm install -g gunbot-monitor@0.0.12` to downgrade to a specific version. But it is not recommended. Hopefully there is a "slim screen option" soon.
