### ISSUE TITLE
Upgrade not working

### ISSUE THREAD

**Issue by vbootstrap** [BeerK0in/gunbot-monitor#6]
I just upgraded to 0.0.19 and now when I run gmon it never gets past the splash screen.

![image](https://cloud.githubusercontent.com/assets/22896025/26517460/06a64760-4267-11e7-88ae-4e4de6392e35.png)

**Comment by vbootstrap** [comment]
I downgraded back to 0.0.17 and it is back to working as expected.

**Comment by BeerK0in** [comment]
What OS do you use?

**Comment by vbootstrap** [comment]
Ubuntu 16.04

Sent from my iPhone

On May 28, 2017, at 3:35 AM, BeerK0in <notifications@github.com<mailto:notifications@github.com>> wrote:


What OS do you use?

-

**Comment by vbootstrap** [comment]
I have done further testing (on a fresh Ubuntu 16.04 VPS).  I installed nodejs 6 and npm.  I installed gunbot-monitor (0.0.20) and ran gmon. with out giving it the -p parameter and I get this:

![image](https://cloud.githubusercontent.com/assets/22896025/26530854/0993c958-43ab-11e7-9f93-7932f14517e9.png)

Seems to be working as expected without data of course. So then I add the -p parameter to my gunbot folder and I am back to:

![image](https://cloud.githubusercontent.com/assets/22896025/26530861/4375a038-43ab-11e7-913f-ecee6ca80a1d.png)

I then run npm install -g gunbot-monitor@0.0.17 to downgrade to 0.0.17 and run the full gmon -p command and I get:

![image](https://cloud.githubusercontent.com/assets/22896025/26530872/b6e95c6c-43ab-11e7-9a58-3c0991a0edbf.png)
 
Works as expected. so it appears that something changed beyond 0.0.17.

**Comment by BeerK0in** [comment]
Could you try 2 things:

1. Use the `-p` parameter and add a tailing slash to your path. `gmon -p /path/`
2. Go to the folder your logs are located an just run `gmon`

Thank you

**Comment by vbootstrap** [comment]
I will try the trailing slash when I get back home but I already tried running cmon from the fun of folder and the same result

Sent from my iPhone

On May 28, 2017, at 5:20 PM, BeerK0in <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you try 2 things:

  1.  Use the -p parameter and add a tailing slash to your path. gmon -p /path/
  2.  Go to the folder your logs are located an just run gmon

Thank you

-

**Comment by vbootstrap** [comment]
[poloniex-BTC_BCN-log.zip](https://github.com/BeerK0in/gunbot-monitor/files/1035776/poloniex-BTC_BCN-log.zip)

Here is one of my log files

**Comment by vbootstrap** [comment]
I did some more investigating.  I am running 18 pairs on gunbot.  After seeing .0.0.20 load when I did not have any logs it got me to thinking.  I move all my logs to another folder and then started moving them back into the correct location one at a time and trying monitor each time.  I got all the way up to 12 pairs and everything worked as expected.  When I added the 13th pair it stopped working.  I do not know if file size has anything to do with the issue, but my log files range from 10MB to 30MB.

**Comment by BeerK0in** [comment]
Could be the profit. For it I have to parse the whole file. But since a lot of people sell (and buy) manually, it is not correct for them anyways. 

So in the current version (0.0.22) I removed the profit column. Can you check please?

**Comment by vbootstrap** [comment]
Yeah that was it. Works like a champ now.

**Comment by BeerK0in** [comment]
I'll try parsing the trade logs and subtracting the sells from the buys. Not sure if the result is the same as parsing the whole log file. But I'll give it a try.

**Comment by BeerK0in** [comment]
v0.0.25 allows you to activate the profit parsing again. Use `-P` parameter.
